version: "3.1"
services:
  db:
    image: postgres:10-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - app-network

  admin:
    image: adminer
    restart: always
    container_name: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  # app:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile
  #   container_name: nextjs-app
  #   restart: always
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
